"""Generate the checked-in vNext OpenAPI document and TypeScript request types."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from fastapi import FastAPI

from api.contracts.vnext import VNEXT_CONTRACT_VERSION
from api.routers.vnext_router import create_vnext_router


ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / 'contracts' / 'vnext.openapi.json'
TYPES_PATH = ROOT / 'frontend' / 'src' / 'vnext' / 'generated' / 'contracts.ts'


def _ref_name(reference: str) -> str:
    return reference.rsplit('/', 1)[-1]


def ts_type(schema: dict[str, Any]) -> str:
    if '$ref' in schema:
        return _ref_name(str(schema['$ref']))
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(value, ensure_ascii=False) for value in schema['enum']) or 'never'
    if 'anyOf' in schema:
        return ' | '.join(ts_type(item) for item in schema['anyOf'])
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts_type({**schema, 'type': item}) for item in kind)
    if kind == 'array':
        item_type = ts_type(schema.get('items') or {})
        return f'Array<{item_type}>'
    if kind == 'object' or 'properties' in schema:
        if schema.get('additionalProperties') and not schema.get('properties'):
            additional = schema['additionalProperties']
            return f'Record<string, {ts_type(additional) if isinstance(additional, dict) else "unknown"}>'
        required = set(schema.get('required') or [])
        fields = []
        for name, definition in (schema.get('properties') or {}).items():
            optional = '' if name in required else '?'
            fields.append(f'    {json.dumps(name, ensure_ascii=False)}{optional}: {ts_type(definition)}')
        if schema.get('additionalProperties'):
            fields.append('    [key: string]: unknown')
        return '{\n' + '\n'.join(fields) + '\n}'
    if kind in {'integer', 'number'}:
        return 'number'
    if kind == 'boolean':
        return 'boolean'
    if kind == 'null':
        return 'null'
    if kind == 'string':
        return 'string'
    return 'unknown'


def build_openapi() -> dict[str, Any]:
    app = FastAPI(title='EasyCode vNext API', version=str(VNEXT_CONTRACT_VERSION))
    app.include_router(create_vnext_router())
    return app.openapi()


def build_types(document: dict[str, Any]) -> str:
    schemas = document.get('components', {}).get('schemas', {})
    lines = [
        '/* eslint-disable */',
        '// Generated by scripts/generate_vnext_contracts.py. Do not edit by hand.',
        f'export const VNEXT_API_CONTRACT_VERSION = {VNEXT_CONTRACT_VERSION} as const',
        '',
    ]
    for name in sorted(schemas):
        lines.append(f'export type {name} = {ts_type(schemas[name])}')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def render() -> tuple[str, str]:
    document = build_openapi()
    openapi = json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + '\n'
    return openapi, build_types(document)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='fail when checked-in contracts have drifted')
    args = parser.parse_args()
    openapi, types = render()
    expected = ((OPENAPI_PATH, openapi), (TYPES_PATH, types))
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in expected if not path.exists() or path.read_text(encoding='utf-8') != content]
        if stale:
            print('vNext contract drift: ' + ', '.join(stale))
            return 1
        print('vNext API contracts are current.')
        return 0
    for path, content in expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8', newline='\n')
        print(f'generated {path.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())

