# core/params/base/image_recognition.py

from .defaults import NODE_DEFAULTS

PARAM_DEFINITIONS = {
    'image_recognition': {
        'label': '图像识别',
        'modes': ['workflow', 'topology'],
        'params': {
            'image_source': {'type': 'file', 'default': '', 'label': '模板图片'},
            'gray_scale': {'type': 'bool', 'default': NODE_DEFAULTS['gray_scale'], 'label': '去除背景干扰 (灰度处理)'},
            'gray_threshold': {
                'type': 'int',
                'default': NODE_DEFAULTS['gray_threshold'],
                'label': '二值化灰度阈值',
                'min': 0,
                'max': 255,
                'step': 1,
                'visible_if': {'field': 'gray_scale', 'operator': 'eq', 'value': True},
            },
            'threshold': {
                'type': 'int',
                'default': NODE_DEFAULTS['threshold'],
                'label': '匹配相似度',
                'suffix': '%',  # ⚡ 增加单位后缀，驱动 ControlNumber 正确显示 0-99%
                'min': 1,
                'max': 100,
            },
            'timeout': {
                'type': 'int',
                'default': NODE_DEFAULTS['timeout'],
                'label': '总超时时间',
                'suffix': 'ms',
                'min': 50,
                'step': 50,
                'help': '这是节点允许运行的总时长，不代表截图或点击间隔。持续模式通常建议 3000ms 以上。',
            },
            'region_type': {
                'type': 'select',
                'options': [
                    {'value': 'fullwindow', 'label': '整个工作面板'},
                    {'value': 'recorded', 'label': '录制时的坐标区域'},
                    {'value': 'custom', 'label': '自定义区域'},
                ],
                'default': NODE_DEFAULTS['region_type'],
                'label': '匹配区域',
            },
            'region_value': {
                'type': 'list_int4_picker',
                'default': [0, 0, 0, 0],
                'label': '匹配区域坐标',
                'visible_if': {'field': 'region_type', 'operator': 'in', 'value': ['recorded', 'custom']},
            },
            'region_reference_size': {'type': 'list_int2', 'default': [0, 0], 'hidden': True},
            'coordinate_space': {'type': 'str', 'default': 'workspace_px', 'hidden': True},
            'execution_mode': {
                'type': 'select',
                'options': [
                    {'value': 'wait_present', 'label': '等待图像出现'},
                    {'value': 'wait_absent', 'label': '等待图像消失'},
                    {'value': 'click_once', 'label': '出现后点击一次'},
                    {'value': 'click_until_absent', 'label': '持续点击直到消失'},
                    {'value': 'click_until_stop', 'label': '持续点击直到停止特征出现'},
                ],
                'default': 'click_once',
                'label': '运行模式',
                'help': [
                    '等待出现/消失用于界面同步，不发送输入。',
                    '持续点击模式在节点内部处理最新画面，不需要在画布上自连循环。',
                    '“直到停止特征出现”会在同一帧优先检查停止特征。',
                ],
            },
            'performance_mode': {
                'type': 'select',
                'options': [
                    {'value': 'auto', 'label': '自动选择（推荐）'},
                    {'value': 'high_speed', 'label': '强制高速，不可用则失败'},
                    {'value': 'standard', 'label': '标准兼容模式'},
                ],
                'default': 'auto',
                'label': '采帧性能模式',
                'help': 'Android 高速模式使用持久视频流；自动模式会明确记录降级原因，不会伪报高速。',
            },
            'stop_image_source': {
                'type': 'file',
                'default': '',
                'label': '停止特征图片',
                'visible_if': {'field': 'execution_mode', 'operator': 'eq', 'value': 'click_until_stop'},
            },
            'stop_threshold': {
                'type': 'int',
                'default': 85,
                'label': '停止特征相似度',
                'suffix': '%',
                'min': 1,
                'max': 100,
                'visible_if': {'field': 'execution_mode', 'operator': 'eq', 'value': 'click_until_stop'},
            },
            'stop_region_type': {
                'type': 'select',
                'options': [
                    {'value': 'fullwindow', 'label': '整个工作面板'},
                    {'value': 'recorded', 'label': '录制时的坐标区域'},
                    {'value': 'custom', 'label': '自定义区域'},
                ],
                'default': 'fullwindow',
                'label': '停止特征区域',
                'visible_if': {'field': 'execution_mode', 'operator': 'eq', 'value': 'click_until_stop'},
            },
            'stop_region_value': {
                'type': 'list_int4_picker',
                'default': [0, 0, 0, 0],
                'label': '停止区域坐标',
                'visible_if': {'field': 'stop_region_type', 'operator': 'in', 'value': ['recorded', 'custom']},
            },
            'stop_region_reference_size': {'type': 'list_int2', 'default': [0, 0], 'hidden': True},
            'stop_gray_scale': {
                'type': 'bool',
                'default': False,
                'label': '停止特征灰度匹配',
                'visible_if': {'field': 'execution_mode', 'operator': 'eq', 'value': 'click_until_stop'},
            },
            'click_interval_ms': {
                'type': 'int',
                'default': 80,
                'label': '最短点击间隔',
                'suffix': 'ms',
                'min': 0,
                'step': 10,
                'visible_if': {
                    'field': 'execution_mode',
                    'operator': 'in',
                    'value': ['click_until_absent', 'click_until_stop'],
                },
                'help': '限制输入速率，防止 Android 处理不过来后积压旧点击。0 表示每个新帧最多点击一次。',
            },
            'max_clicks': {
                'type': 'int',
                'default': 100,
                'label': '最大点击次数',
                'min': 1,
                'max': 100000,
                'visible_if': {
                    'field': 'execution_mode',
                    'operator': 'in',
                    'value': ['click_until_absent', 'click_until_stop'],
                },
            },
            'present_stable_frames': {
                'type': 'int',
                'default': 1,
                'label': '出现稳定帧数',
                'min': 1,
                'max': 20,
                'visible_if': {
                    'field': 'execution_mode',
                    'operator': 'in',
                    'value': ['wait_present', 'click_once'],
                },
            },
            'absent_stable_frames': {
                'type': 'int',
                'default': 2,
                'label': '消失稳定帧数',
                'min': 1,
                'max': 20,
                'visible_if': {
                    'field': 'execution_mode',
                    'operator': 'in',
                    'value': ['wait_absent', 'click_until_absent'],
                },
                'help': '连续多帧未识别才判定消失，可避免动画闪烁或偶发漏帧导致误跳转。',
            },
            'stop_stable_frames': {
                'type': 'int',
                'default': 1,
                'label': '停止特征稳定帧数',
                'min': 1,
                'max': 20,
                'visible_if': {'field': 'execution_mode', 'operator': 'eq', 'value': 'click_until_stop'},
            },
            'frame_interval_ms': {
                'type': 'int',
                'default': 0,
                'label': '最短采帧间隔',
                'suffix': 'ms',
                'min': 0,
                'step': 5,
                'help': '0 表示捕获后立即请求下一帧；调大可降低 CPU/设备负载。',
            },
            'match_scales': {
                'type': 'str',
                'default': '',
                'label': '节点匹配尺度',
                'help': '留空继承项目设置。分辨率固定的高速流程建议填写 1.0，避免多尺度重复计算。',
            },
            },
    }
}
